/**
 * User-Aware Asset Library UI Components
 * Owner: George
 * 
 * React components for managing assets with user-based access control
 */

import React, { useState, useEffect, useCallback } from 'react';
import { 
  Upload, 
  Search, 
  Share2, 
  Download, 
  Eye, 
  Edit, 
  Trash2, 
  Star, 
  MoreVertical,
  Users,
  Globe,
  Lock,
  Clock,
  HardDrive,
  Server
} from 'lucide-react';
import { UserAwareAssetManager } from '../../library/UserAwareAssetManager';
import type { 
  User, 
  EnhancedAssetOwnership,
  AssetAnalytics
} from '../../library/UserAwareAssetTypes';
import type { LibraryAsset } from '../../library/types';

interface AssetLibraryProps {
  user: User;
  onAssetSelect: (asset: LibraryAsset) => void;
  onAssetUpload: (files: File[]) => void;
}

interface AssetCardProps {
  asset: LibraryAsset;
  ownership: EnhancedAssetOwnership;
  analytics?: AssetAnalytics;
  onSelect: () => void;
  onShare: () => void;
  onDownload: () => void;
  onEdit: () => void;
  onDelete: () => void;
  onToggleFavorite: () => void;
}

interface AssetUploadZoneProps {
  onUpload: (files: File[]) => void;
  maxFiles?: number;
  maxSize?: number; // MB
  allowedTypes?: string[];
}

// AssetShareDialogProps interface removed - unused

/**
 * Main Asset Library Component
 */
export const UserAwareAssetLibrary: React.FC<AssetLibraryProps> = ({
  user,
  onAssetSelect,
  onAssetUpload: _onAssetUpload
}) => {
  const [assetManager] = useState(() => UserAwareAssetManager.getInstance());
  const [assets, setAssets] = useState<LibraryAsset[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filters, setFilters] = useState({
    ownership: 'all' as 'own' | 'shared' | 'public' | 'all',
    assetTypes: [] as string[],
    tags: [] as string[]
  });
  const [showUploadZone, setShowUploadZone] = useState(false);

  useEffect(() => {
    initializeAssetManager();
  }, []);

  useEffect(() => {
    loadAssets();
  }, [searchQuery, filters]);

  const initializeAssetManager = async () => {
    try {
      await assetManager.initialize(user);
      setLoading(false);
    } catch (error) {
      console.error('Failed to initialize asset manager:', error);
      setLoading(false);
    }
  };

  const loadAssets = async () => {
    try {
      const userAssets = await assetManager.getUserAssets({
        ownership: filters.ownership,
        assetTypes: filters.assetTypes,
        tags: filters.tags,
        searchQuery
      });
      setAssets(userAssets);
    } catch (error) {
      console.error('Failed to load assets:', error);
    }
  };

  const handleAssetUpload = async (files: File[]) => {
    try {
      // Create ownership for uploaded assets
      const ownership: EnhancedAssetOwnership = {
        ownerId: user.id,
        ownerType: 'user',
        createdAt: new Date(),
        permissions: {
          public: false,
          teamShare: true,
          organizationShare: user.organizationId ? true : false,
          allowDownload: true,
          allowModify: true
        },
        visibility: user.preferences.defaultAssetVisibility,
        sharingSettings: {
          allowDownload: true,
          allowModify: true,
          allowShare: true
        },
        accessHistory: [],
        collaborators: []
      };

      // Process each file
      for (const file of files) {
        const asset: LibraryAsset = {
          id: '', // Will be generated by manager
          name: file.name,
          domain: 'custom',
          assetClass: 'structures',
          assetType: file.type.split('/')[0] || 'unknown',
          loaderType: getLoaderType(file.name),
          filePath: '', // Will be set by manager
          fileSize: Math.round(file.size / (1024 * 1024)), // Convert to MB
          tags: [],
          searchKeywords: [file.name],
          description: `Uploaded by ${user.name}`,
          source: 'local',
          usageCount: 0,
          lastUsed: new Date(),
          isFavorite: false
        };

        await assetManager.saveAsset(asset, ownership);
      }

      // Reload assets
      await loadAssets();
      setShowUploadZone(false);
    } catch (error) {
      console.error('Failed to upload assets:', error);
    }
  };

  const getLoaderType = (filename: string): any => {
    const ext = filename.split('.').pop()?.toLowerCase();
    switch (ext) {
      case 'urdf': return 'urdf';
      case 'glb': return 'glb';
      case 'gltf': return 'gltf';
      case 'stl': return 'stl';
      case 'obj': return 'obj';
      case 'dwg': return 'dwg';
      case 'jt': return 'jt';
      default: return 'primitive';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <span className="ml-2 text-gray-600">Loading asset library...</span>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 p-4">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-semibold text-gray-900">Asset Library</h2>
          <button
            onClick={() => setShowUploadZone(true)}
            className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Upload className="w-4 h-4 mr-2" />
            Upload Assets
          </button>
        </div>

        {/* Search and Filters */}
        <div className="flex items-center space-x-4">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
            <input
              type="text"
              placeholder="Search assets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
          
          <select
            value={filters.ownership}
            onChange={(e) => setFilters(prev => ({ ...prev, ownership: e.target.value as any }))}
            className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option value="all">All Assets</option>
            <option value="own">My Assets</option>
            <option value="shared">Shared with Me</option>
            <option value="public">Public Assets</option>
          </select>
        </div>
      </div>

      {/* Asset Grid */}
      <div className="flex-1 p-4 overflow-auto">
        {assets.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-64 text-gray-500">
            <HardDrive className="w-12 h-12 mb-4 text-gray-300" />
            <h3 className="text-lg font-medium mb-2">No assets found</h3>
            <p className="text-sm text-center">
              {searchQuery || filters.ownership !== 'all' 
                ? 'Try adjusting your search or filters'
                : 'Upload your first asset to get started'
              }
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {assets.map((asset) => (
              <AssetCard
                key={asset.id}
                asset={asset}
                ownership={asset.customMetadata?.ownership as EnhancedAssetOwnership}
                onSelect={() => onAssetSelect(asset)}
                onShare={() => {/* TODO: Implement share dialog */}}
                onDownload={() => {/* TODO: Implement download */}}
                onEdit={() => {/* TODO: Implement edit */}}
                onDelete={() => {/* TODO: Implement delete */}}
                onToggleFavorite={() => {/* TODO: Implement favorite toggle */}}
              />
            ))}
          </div>
        )}
      </div>

      {/* Upload Zone Modal */}
      {showUploadZone && (
        <AssetUploadZone
          onUpload={handleAssetUpload}
          maxFiles={10}
          maxSize={100} // 100MB
          allowedTypes={['urdf', 'glb', 'gltf', 'stl', 'obj', 'dwg', 'jt']}
        />
      )}
    </div>
  );
};

/**
 * Individual Asset Card Component
 */
const AssetCard: React.FC<AssetCardProps> = ({
  asset,
  ownership,
  analytics,
  onSelect,
  onShare,
  onDownload,
  onEdit,
  onDelete,
  onToggleFavorite
}) => {
  const [showActions, setShowActions] = useState(false);

  const getVisibilityIcon = () => {
    switch (ownership?.visibility) {
      case 'public': return <Globe className="w-4 h-4 text-green-500" />;
      case 'team': return <Users className="w-4 h-4 text-blue-500" />;
      case 'organization': return <Server className="w-4 h-4 text-purple-500" />;
      default: return <Lock className="w-4 h-4 text-gray-500" />;
    }
  };

  const getFileSizeText = () => {
    if (!asset.fileSize) return 'Unknown size';
    if (asset.fileSize < 1) return `${Math.round(asset.fileSize * 1024)} KB`;
    return `${asset.fileSize.toFixed(1)} MB`;
  };

  return (
    <div 
      className="bg-white rounded-lg border border-gray-200 hover:shadow-md transition-shadow cursor-pointer"
      onClick={onSelect}
    >
      {/* Thumbnail */}
      <div className="aspect-square bg-gray-100 rounded-t-lg flex items-center justify-center">
        {asset.thumbnailUrl ? (
          <img 
            src={asset.thumbnailUrl} 
            alt={asset.name}
            className="w-full h-full object-cover rounded-t-lg"
          />
        ) : (
          <div className="text-gray-400">
            <HardDrive className="w-8 h-8 mx-auto mb-2" />
            <span className="text-xs">{asset.loaderType.toUpperCase()}</span>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="p-3">
        <div className="flex items-start justify-between mb-2">
          <h3 className="font-medium text-gray-900 text-sm truncate flex-1">
            {asset.name}
          </h3>
          <div className="flex items-center space-x-1 ml-2">
            {getVisibilityIcon()}
            <button
              onClick={(e) => {
                e.stopPropagation();
                onToggleFavorite();
              }}
              className="text-gray-400 hover:text-yellow-500 transition-colors"
            >
              <Star className={`w-4 h-4 ${asset.isFavorite ? 'fill-current text-yellow-500' : ''}`} />
            </button>
          </div>
        </div>

        <div className="flex items-center justify-between text-xs text-gray-500 mb-2">
          <span>{getFileSizeText()}</span>
          <span>{asset.loaderType.toUpperCase()}</span>
        </div>

        {asset.description && (
          <p className="text-xs text-gray-600 mb-2 line-clamp-2">
            {asset.description}
          </p>
        )}

        {/* Tags */}
        {asset.tags.length > 0 && (
          <div className="flex flex-wrap gap-1 mb-2">
            {asset.tags.slice(0, 3).map((tag: string, index: number) => (
              <span 
                key={index}
                className="px-2 py-1 bg-gray-100 text-gray-600 text-xs rounded"
              >
                {tag}
              </span>
            ))}
            {asset.tags.length > 3 && (
              <span className="px-2 py-1 bg-gray-100 text-gray-600 text-xs rounded">
                +{asset.tags.length - 3}
              </span>
            )}
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-1">
            <button
              onClick={(e) => {
                e.stopPropagation();
                onDownload();
              }}
              className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
              title="Download"
            >
              <Download className="w-4 h-4" />
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation();
                onShare();
              }}
              className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
              title="Share"
            >
              <Share2 className="w-4 h-4" />
            </button>
          </div>

          <div className="relative">
            <button
              onClick={(e) => {
                e.stopPropagation();
                setShowActions(!showActions);
              }}
              className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
            >
              <MoreVertical className="w-4 h-4" />
            </button>

            {showActions && (
              <div className="absolute right-0 top-8 bg-white border border-gray-200 rounded-lg shadow-lg z-10 min-w-32">
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onEdit();
                    setShowActions(false);
                  }}
                  className="w-full px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-50 flex items-center"
                >
                  <Edit className="w-4 h-4 mr-2" />
                  Edit
                </button>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onDelete();
                    setShowActions(false);
                  }}
                  className="w-full px-3 py-2 text-left text-sm text-red-600 hover:bg-red-50 flex items-center"
                >
                  <Trash2 className="w-4 h-4 mr-2" />
                  Delete
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Analytics */}
        {analytics && (
          <div className="mt-2 pt-2 border-t border-gray-100">
            <div className="flex items-center justify-between text-xs text-gray-500">
              <span className="flex items-center">
                <Eye className="w-3 h-3 mr-1" />
                {analytics.usageStats.totalViews}
              </span>
              <span className="flex items-center">
                <Clock className="w-3 h-3 mr-1" />
                {new Date(analytics.usageStats.lastUsed).toLocaleDateString()}
              </span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

/**
 * Asset Upload Zone Component
 */
const AssetUploadZone: React.FC<AssetUploadZoneProps> = ({
  onUpload,
  maxFiles = 10,
  maxSize = 100,
  allowedTypes = []
}) => {
  const [dragActive, setDragActive] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const [errors, setErrors] = useState<string[]>([]);

  const handleDrag = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    const droppedFiles = Array.from(e.dataTransfer.files);
    processFiles(droppedFiles);
  }, []);

  const handleFileInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const selectedFiles = Array.from(e.target.files);
      processFiles(selectedFiles);
    }
  };

  const processFiles = (newFiles: File[]) => {
    const errors: string[] = [];
    const validFiles: File[] = [];

    newFiles.forEach(file => {
      // Check file count
      if (files.length + validFiles.length >= maxFiles) {
        errors.push(`Maximum ${maxFiles} files allowed`);
        return;
      }

      // Check file size
      if (file.size > maxSize * 1024 * 1024) {
        errors.push(`${file.name} exceeds ${maxSize}MB limit`);
        return;
      }

      // Check file type
      const fileExt = file.name.split('.').pop()?.toLowerCase();
      if (allowedTypes.length > 0 && fileExt && !allowedTypes.includes(fileExt)) {
        errors.push(`${file.name} is not a supported file type`);
        return;
      }

      validFiles.push(file);
    });

    setErrors(errors);
    setFiles(prev => [...prev, ...validFiles]);
  };

  const removeFile = (index: number) => {
    setFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleUpload = () => {
    if (files.length > 0) {
      onUpload(files);
      setFiles([]);
      setErrors([]);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[80vh] overflow-auto">
        <h3 className="text-lg font-semibold mb-4">Upload Assets</h3>

        {/* Drop Zone */}
        <div
          className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
            dragActive 
              ? 'border-blue-500 bg-blue-50' 
              : 'border-gray-300 hover:border-gray-400'
          }`}
          onDragEnter={handleDrag}
          onDragLeave={handleDrag}
          onDragOver={handleDrag}
          onDrop={handleDrop}
        >
          <Upload className="w-12 h-12 mx-auto mb-4 text-gray-400" />
          <p className="text-lg font-medium text-gray-900 mb-2">
            Drop files here or click to browse
          </p>
          <p className="text-sm text-gray-500 mb-4">
            Maximum {maxFiles} files, {maxSize}MB each
          </p>
          <input
            type="file"
            multiple
            onChange={handleFileInput}
            className="hidden"
            id="file-upload"
            accept={allowedTypes.map(type => `.${type}`).join(',')}
          />
          <label
            htmlFor="file-upload"
            className="inline-block px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 cursor-pointer"
          >
            Choose Files
          </label>
        </div>

        {/* File List */}
        {files.length > 0 && (
          <div className="mt-4">
            <h4 className="font-medium mb-2">Selected Files ({files.length})</h4>
            <div className="space-y-2 max-h-40 overflow-auto">
              {files.map((file, index) => (
                <div key={index} className="flex items-center justify-between p-2 bg-gray-50 rounded">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-900 truncate">
                      {file.name}
                    </p>
                    <p className="text-xs text-gray-500">
                      {(file.size / (1024 * 1024)).toFixed(1)} MB
                    </p>
                  </div>
                  <button
                    onClick={() => removeFile(index)}
                    className="ml-2 text-red-500 hover:text-red-700"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Errors */}
        {errors.length > 0 && (
          <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg">
            <h4 className="font-medium text-red-800 mb-2">Errors:</h4>
            <ul className="text-sm text-red-700 space-y-1">
              {errors.map((error, index) => (
                <li key={index}>• {error}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Actions */}
        <div className="flex justify-end space-x-3 mt-6">
          <button
            onClick={() => {
              setFiles([]);
              setErrors([]);
            }}
            className="px-4 py-2 text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            onClick={handleUpload}
            disabled={files.length === 0}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Upload {files.length} File{files.length !== 1 ? 's' : ''}
          </button>
        </div>
      </div>
    </div>
  );
};

